### ISSUE TITLE
CUDA not detected

### ISSUE THREAD

**Issue by privacyadmin** [TNTwise/REAL-Video-Enhancer#13]
Hi,

Before I start, thank you for making a project like this possible. If anything, I am deeply appreciate of it as  someone coming from Windows with little knowledge in Linux recently.

For the problem:
I am having issue getting RVE to pickup my CUDA installation. My OS is LMDE running on 6.1.0-21. I installed my nvidia driver and CUDA using sudo apt install nvidia-driver && sudo apt install nvidia-cuda-toolkit.

CUDA seems to be detected when I run nvcc --version though

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

Can advise what other steps are necessary to get RVE to detect CUDA?

This is a Flatpak installation btw if it helps.

Thank you

**Comment by TNTwise** [comment]
Flatpak and cuda do not work yet. You will have to download the cuda tar xz file from the releases tab, and run the executable.

**Comment by privacyadmin** [comment]
Noted on the limitation. I have downloaded the release and able to detect CUDA now. 
Thank you for the patience and your work for the public good. Appreciate it.
