### ISSUE TITLE
Is it normal that Frames Extraction is incredibly slow at max 8 frames per second?

### ISSUE THREAD

**Issue by ProtoBelisarius** [TNTwise/REAL-Video-Enhancer#14]
Before submitting an issue, please confirm it meets all the criteria
- [ x] I am using the Flatpak or stable AppImage release, if you are on the BETA, please create an issue in that respective repository.

**Describe the bug**
As mentioned in the title, frame extraction takes ages. Is there a setting for multithreading? Because it only uses one of 24 threads. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If the application generates a log, please upload it here.
Logs folder on Flatpak: ``/home/$USER/.var/app/io.github.tntwise.REAL-Video-Enhancer/logs/``
Logs folder on AppImage: ``/home/$USER/.local/share/REAL-Video-Enhancer/logs/``

**Desktop (please complete the following information):**
- CPU: 5900X, 64GB RAM 
- OS: [Arch]
 - Version [AppImage]
 
**GPU**
RX 6800XT, ncnn

**Additional context**

**Comment by TNTwise** [comment]
It just uses ffmpeg for frame extraction, if it's set to webp this can take a while. In the pre-release, I have updated rife to be used without frame extraction, if you want to try that out. If you want to use frame extraction, jpg is recommended for speed.

**Comment by ProtoBelisarius** [comment]
Yea, jpg works much better but how much worse is the degradation with that? At what quality setting is the jpg compression set? I already have a 1080p source and don't want to upscale.

**Comment by TNTwise** [comment]
I have it set to the closest to lossless setting, but it will have compression, shouldn't be too noticeable in the output video, though.

**Comment by ProtoBelisarius** [comment]
Ok, thank you for the prompt answers!
