### ISSUE TITLE
Can you use waifu2x vulkan ?

### ISSUE THREAD

**Issue by greatlord** [TNTwise/REAL-Video-Enhancer#15]
Hi
Can you implement waifu2x vulkan as well ??
https://github.com/nihui/waifu2x-ncnn-vulkan

**Comment by TNTwise** [comment]
Waifu2x should be in there, but I would recommend using something like span.

**Comment by greatlord** [comment]
thanks I did not test it did run on vulkan or not, it is their 
I close it now sorry i open a issue when it was none
