### ISSUE TITLE
CLI support?

### ISSUE THREAD

**Issue by Sparkyu222** [TNTwise/REAL-Video-Enhancer#17]
I am currently running a headless server and would love to use your application on it. However, I noticed that there isn't a command-line interface available at the moment. I made several searches on how to use this app in CLI but couldn't find any relevant information or documentation.

I wanted to ask if there are any plans to introduce CLI support for this app? Having a CLI would greatly enhance its usability in environments where a GUI is not available or practical.

**Comment by TNTwise** [comment]
I have made a CLI for the upcoming release. It is in the backend folder of the v2 branch.

**Comment by Sparkyu222** [comment]
Alright I'll wait and look into it, thank you for the hard work!
