### ISSUE TITLE
Input file becomes "deselected" after running enhancement for one time

### ISSUE THREAD

**Issue by RDKRACZ** [TNTwise/REAL-Video-Enhancer#2]
Before submitting an issue, please confirm it meets all the criteria
- [x] I am on a distribution that is at least Ubuntu 20.04+, this means that your distros packages are the same as, or more up-to-date than Ubuntu 20.04.
- [x] I am using the Flatpak or stable AppImage release, if you are on the BETA, please create an issue in that respective repository.

**Describe the bug**
After selecting the input and starting the enhancement the next time I want to change some settings and repeat the process I'm met with the error shown below.

**To Reproduce**

**Expected behavior**
The file should remain selected no matter if the enhancement was already done on the file.

**Screenshots**
![image](https://github.com/TNTwise/REAL-Video-Enhancer/assets/43277609/af7277e9-2c9f-4ae6-9ee8-0928c7128e7d)

**Logs**
Logs folder on Flatpak: ``/home/$USER/.var/app/io.github.tntwise.REAL-Video-Enhancer/logs/``
Logs folder on AppImage: ``/home/$USER/.local/share/REAL-Video-Enhancer/logs/``

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Version: Flatpak
 
**GPU**
RX 6600 M

**Additional context**

**Comment by TNTwise** [comment]
Sorry for the late response, but I have removed the line that reset the input file after rendering, Don't remember why I added it in the first place, but I will test with that line removed and see if any bugs pop up. Thank you.

**Comment by TNTwise** [comment]
Fixed in 1.0.6, if there is still an issue I will reopen this. Closing for now.
