### ISSUE TITLE
I downloaded the flatpak version but it doesn't save the videos

### ISSUE THREAD

**Issue by chocof14n** [TNTwise/REAL-Video-Enhancer#21]

**Comment by TNTwise** [comment]
Make sure you have permissions to the videos output folder, this has issues on certain distros.

**Comment by TNTwise** [comment]
https://github.com/TNTwise/REAL-Video-Enhancer/issues/8

**Comment by chocof14n** [comment]
How do I give permission to the folder? I have tried but I am new to Linux.
I am using mx-linux in its latest version (debian12)

**Comment by TNTwise** [comment]
sudo flatpak override io.github.tntwise.REAL-Video-Enhancer --filesystem=/home/$USER/Videos

Or use the appimage which doesn't have a sandbox.

**Comment by chocof14n** [comment]
al final lo resolvi usando flatseal

**Comment by chocof14n** [comment]
I finally solved it using flatseal
