### ISSUE TITLE
Frame count does not update inside status box 

### ISSUE THREAD

**Issue by TheLWD** [TNTwise/REAL-Video-Enhancer#25]
Not sure if bug or feature will draw attention to it anyway :)

![image](https://github.com/user-attachments/assets/87f8410f-fd31-4dd2-819d-ccc662e052f6)

**Comment by TNTwise** [comment]
Frame count is just the number of frames in a video, I could specify it better though

**Comment by TNTwise** [comment]
Made it less confusing now in latest pre release
