### ISSUE TITLE
Add check mark symbol in to toggles

### ISSUE THREAD

**Issue by CcMenta** [TNTwise/REAL-Video-Enhancer#26]
I always had issue when something only uses colors for showing what is selected or toggled, in case there are more than 2 select-able it's easy to tell which is selected because the selected one have different color than the not selected ones, but in case of toggles where multiple can be enabled and disabled I don't know which is enabled and which are disabled, adding a check mark in the toggle box if the option is enabled would make it less confusing.

**Comment by TNTwise** [comment]
Checkboxes are hard to customize, I'll look into it but I like the current design.
