### ISSUE TITLE
MacOS v2.0 Alpha3 not loading

### ISSUE THREAD

**Issue by painterize** [TNTwise/REAL-Video-Enhancer#28]
I cannot get any of the Alpha versions to work.

I'm on a 2019 Intel Mac.

The stable release 1.2 works fine - could you create a standalone binary file for the Alpha release too?

**Comment by TNTwise** [comment]
MacOS is really broken.

**Comment by painterize** [comment]
Please keep MacOS support going! At least for a stable version 2.0.

**Comment by TNTwise** [comment]
https://lunduke.locals.com/post/6304352/apple-removes-ability-to-run-unsigned-apps-in-macos-15-1
MacOS support wont be returning, as apple seems to be closing down the ecosystem even more.

**Comment by TNTwise** [comment]
added it back in 2.2.5, I am not completely sure if it works tho
