### ISSUE TITLE
Which version is the fastest reasoning?

### ISSUE THREAD

**Issue by lgthappy** [TNTwise/REAL-Video-Enhancer#29]
Hello, I have some questions: I would like to know which version of the model is recommended if I want to complete the x2 video frame filling as fast as possible? Is it possible to achieve real-time results by converting to tensorrt, and how many milliseconds does it take per frame? Do you have any related code?

**Comment by TNTwise** [comment]
4.6 or 4.22-lite(if you are on the alpha 3 build) TensorRT is the fastest inference method, but it has to build an engine at every unique resolution you render at.
