### ISSUE TITLE
Run on Windows?

### ISSUE THREAD

**Issue by RRomeo93** [TNTwise/REAL-Video-Enhancer#3]
Hi, possibly to run ur software on windows? if yes how?

**Comment by TNTwise** [comment]
Unfortunately, everything here is Linux specific. There is other software like flowframes, enhancer, and others that can do the same function on windows.

**Comment by TNTwise** [comment]
My friend tested under WSL, and it works with the appimage. Unfortunately, it seems like GPU inference doesn't work because vulkan is unsupported, so you are stuck on CPU inference.

**Comment by TNTwise** [comment]
V2 will receive windows support.

**Comment by TNTwise** [comment]
Windows alpha has released!
