### ISSUE TITLE
Video quality option is not working (alpha4 windows version）

### ISSUE THREAD

**Issue by gman771** [TNTwise/REAL-Video-Enhancer#32]
The video quality option is not working.No matter how I set it, it always goes back to very high,the actual exported video has a CRF of 15.
In addition, it is hoped that more customizable options for video output can be opened up, such as CRF values, color formats, and so on.

**Comment by TNTwise** [comment]
Fixed in latest pre release.

**Comment by gman771** [comment]
thanks for your response
