### ISSUE TITLE
result in a black image in the video

### ISSUE THREAD

**Issue by idanka** [TNTwise/REAL-Video-Enhancer#33]
All package 

**Describe the bug**
All applications result in a black image in the video

**To Reproduce**
open video, pytorch, upscale, realistic 2x, no tiling, no bench

Resolution: 640x480 -> 1280x960
Bitrate: 597
Encoder: VP90
Container: .mkv
Frame Count: 6611

**Expected behavior**
...

**Screenshots**
![20241015_084615](https://github.com/user-attachments/assets/ee80c7cc-ff42-45a6-8246-fbbe4244ea20)

**Logs**
[log_2024-10-15:06:10:57.txt](https://github.com/user-attachments/files/17373815/log_2024-10-15.06.10.57.txt)
[frontend_log.txt](https://github.com/user-attachments/files/17373817/frontend_log.txt)

**Desktop (please complete the following information):**
 - OS: Manjaro KDE
 - Operating System: Manjaro Linux 
 - KDE Plasma Version: 6.1.5
 - KDE Frameworks Version: 6.6.0
 - Qt Version: 6.7.2
 - Kernel Version: 6.11.2-4-MANJARO (64-bit)
 - Graphics Platform: X11
 - Processors: 4 × Intel® Core™ i5-4570 CPU @ 3.20GHz
 - Memory: 15.5 GiB of RAM
 - Graphics Processor: NVIDIA GeForce GTX 1650/PCIe/SSE2
 - Manufacturer: FUJITSU
 - Product Name: ESPRIMO P520
 
 - Version REAL-Video-Enhancer
 -- REAL-Video-Enhancer-CUDA-Linux.tar.xz, 
 -- REAL-Video-Enhancer-NCNN-Linux-x86_64.AppImage
 -- REAL Video Enhancer 2.0 Alpha 4
 
**GPU**
nvidia GeForce GTX 1650 / 550.120 (cuda12.6.1., cudnn9.2.1.18-1, nccl2.21.5-1)

**Additional context**
Video all frame black image.

> Codformer problem:
> "I resolved the issue with the following trick.
> just add these two lines after the import statements in the file "inference_codeformer.py" and save it.
> 
> torch.backends.cudnn.benchmark = True
> torch.backends.cudnn.enabled = True
> 
> The issue has something to do with float16 computational performance in all 16XX cards. The above trick seems to have resolved it. Using the same trick, I am able to run Stable Diffusion as well without using any optimization arguments."
> 
> Linux add line .bashrc and restart os. Definitely slower but it works!
> export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256'
> 
> -------------------
> Windows: set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
> Linux: export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
> use video enhancer: 
> Linux: export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:64'

**Comment by TNTwise** [comment]
Should be fixed in 2.0 releasing later today, thank you for reporting!
