### ISSUE TITLE
Proper way to update alphas?

### ISSUE THREAD

**Issue by zelenooki87** [TNTwise/REAL-Video-Enhancer#34]
hi. Thank you for wonderful project and Windows support!
I installed latest alpha, but to be sure, after some time if I need to update, should I remove old version /folders or cope&replace old?

**Comment by TNTwise** [comment]
It is best to delete older versions and start fresh, as each alpha upgrade has breaking changes.

**Comment by zelenooki87** [comment]
Ok. 
Why I dont have IFrnet listed as interpolation engine? Only Rife.
Thanks

**Comment by TNTwise** [comment]
Ifrnet is old, rife is faster and produces better results. Putting ifrnet into the current version of rve is not unreasonable, but not something I am going to do at least before the release of v2. I would recommend rife 4.18 instead of ifrnet.

**Comment by zelenooki87** [comment]
Okay. Thanks
