### ISSUE TITLE
Weird issue when running in docker

### ISSUE THREAD

**Issue by Joly0** [TNTwise/REAL-Video-Enhancer#37]
Before submitting an issue, please confirm it meets all the criteria
- [X] I am on a distribution that is at least Ubuntu 20.04+, this means that your distros packages are the same as, or more up to date than Ubuntu 20.04.
- [ ] I am using the Flatpak or stable AppImage release, if you are on the BETA, please create an issue in that respective repository.

**Describe the bug**
So, i am building a docker image for this cool tool which will make it able to be run in a browser, though i am having a weird issue.
The baseimage i am using is debian 12 and i am installing python3.11. So far no issues. I install numpy, opencv-python and tqdm and that works without any issues aswell.
Now the problem is, that when i run the container, your application starts and is shown in the webui as it should, but iit displays this:
![grafik](https://github.com/user-attachments/assets/18cbdfec-61aa-41a2-80ea-819dc80377cf)
and the logs show this:
```
System Information: 
OS: Ubuntu 24.04 x86_64
CPU: AMD Ryzen 9 7950X 16-Core Processor
GPU: NVIDIA Corporation AD106 [GeForce RTX 4060 Ti 16GB] (rev a1)
16
RAM: 61.96 GB
Available Disk Space: 283.2GB
-------------------------------------------
Software Information: 
REAL Video Enhancer Version: 2.0
Available Backends: []
Half precision support: False

 
Getting total models, method: Interpolate backend: 
```

So no backend is found, which is to be expected, as there is no ncnn, torch or tensorrt installed.
The weird thing now is, if i change the install commands, so for example opencv-python is not installed, then the tool mentions, that cv2 couldnt be imported like this:
 ```
 Starting /app/bin/REAL-Video-Enhancer
/app/backend Does not exist!
Downloading backend
Extracting backend
Extracting: /app/backend.tar.gz
Downloading FFMpeg
Downloading: https://github.com/TNTwise/real-video-enhancer-models/releases/download/models/ffmpeg
Downloading Python
Downloading: https://github.com/indygreg/python-build-standalone/releases/download/20240814/cpython-3.11.9+20240814-x86_64-unknown-linux-gnu-install_only.tar.gz
Extracting: /app/python/python.tar.gz
Traceback (most recent call last):
File "/app/backend/rve-backend.py", line 5, in <module>
from src.RenderVideo import Render
File "/app/backend/src/RenderVideo.py", line 7, in <module>
from .FFmpeg import FFMpegRender
File "/app/backend/src/FFmpeg.py", line 1, in <module>
import cv2
ModuleNotFoundError: No module named 'cv2'
invalid syntax (<string>, line 0)
 ```
but otherwise runs just fine and shows this:
![grafik](https://github.com/user-attachments/assets/84e90d58-1a16-4634-998b-9b99646ef5b0)
So it actually gives me the option to install any backend.

**To Reproduce**
Install debian 12, install python3.11 aswell as opencv-python and run this application. See error

**Expected behavior**
Should give me the same option to install the backend as if i didnt have opencv-python installed.

**Additional context**
So my goal here is, to get rid of the error message that shows the failed cv2 import that might confuse people but also give the users the option to install any backend at startup, without having to pre-install for example torch, which would solve the issue, but would make the docker image way larger and would force that method to users unless they install a separate backend through the settings.

And as a side-note, i am running the latest stable version from the releases page in the container

**Comment by TNTwise** [comment]
fixed, patch will be in preview build

**Comment by Joly0** [comment]
Nice, that was quick, thanks. Will try it out as soon as its available and report back if it works

**Comment by Joly0** [comment]
Ok, i built the application from source inside the image and it seems like its working. So thanks again

**Comment by Joly0** [comment]
Btw, is it possible to run the application maximized? Whatever i try, it always starts in a normal sized window, but it would be better, if it were maximized for what i am trying to achieve

So would be cool if i coukd start it by running `./REAL-Video-Enhancer --maximized` or `./REAL-Video-Enhancer --fullscreen`

**Comment by TNTwise** [comment]
Its possible to make it maximized on the desktop, I don't have a cli argument for it to start like that though.

**Comment by Joly0** [comment]
Yes, i have seen that its possible to maximize it normally, though would still be neat if i could start it maximized with an argument.


If thats something you dont want to implement or cant implement than i guess i have to live with it. Otherwise would be great if it was possible :)

**Comment by TNTwise** [comment]
It shouldn't be too hard, I will look into it within the next day or so.

**Comment by TNTwise** [comment]
done, should be in latest preview soon

**Comment by Joly0** [comment]
Btw, thanks to your assistance i was able to get the docker images working. I have to adjust the startup script a little and add documentantion on how to run them, but otherwise its working and it will automatically build new versions regularly
https://github.com/Joly0/REAL-Video-Enhancer-docker

So thanks again for your help, i appreciate it and the work you are putting into this project.
