### ISSUE TITLE
Support for custom .pth models

### ISSUE THREAD

**Issue by Joly0** [TNTwise/REAL-Video-Enhancer#38]
Hey, it would be great if it were possible (maybe through a separate folder from the normal "models" folder) to load custom model files.
I would like to test different models from for example here https://openmodeldb.info/ and see their results for various video types (realistic, animation, art, etc), but thats currently not possible, as there seems to only exist a pre-defined hard-coded list of existing models

**Comment by TNTwise** [comment]
Planned for 2.1

**Comment by zelenooki87** [comment]
So does that mean we could import any spandrel architecture compatible model in v2.1?
When you plan to realease 2.1?
Thanks

**Comment by TNTwise** [comment]
Yes, and 2.1 will be released by the end of November.

**Comment by TNTwise** [comment]
Added in latest 2.1 pre-release.

**Comment by Joly0** [comment]
Hey, thanks for implementing this. I am trying to get it working in my docker image, though i am facing 2 issues.
The first is rather simple. So i mapped the custom_models folder to the host and thought, i could drop the models in that folder and could import them then. But doing so results in this error:
```
Traceback (most recent call last):
  File "/tmp/REAL-Video-Enhancer/src/ui/DownloadTab.py", line 53, in <lambda>
  File "REAL-Video-Enhancer.py", line 452, in importCustomModel
  File "/tmp/REAL-Video-Enhancer/src/Util.py", line 235, in copyFile
  File "/usr/local/lib/python3.11/shutil.py", line 431, in copy
  File "/usr/local/lib/python3.11/shutil.py", line 236, in copyfile
shutil.SameFileError: '/app/custom_models/RealESRGAN_x4plus_anime_6B.pth' and '/app/custom_models/RealESRGAN_x4plus_anime_6B.pth' are the same file
```
So i guess the code tries to move the same file to the same place and therefore it fails. Would be great, if i didnt have to have a second folder, just to upload custom models to and could just place them in the custom_models folder. Not sure if this is possible, but would be neat :)

The second issue is more confusing for me. So i dropped a custom model into the "Videos" folder (so i could import it) and imported it, but the application hang completely. I couldnt click anything or do anything. I had to restart the container to get it working again. Atleast The model seemed to be imported afterwards, but any idea what might cause this issue?

**Comment by Joly0** [comment]
Ok, i figured out what the second problem is:
![grafik](https://github.com/user-attachments/assets/aed85d9a-d420-45ce-aeac-9345e35eed5b)
Its this window, that is not shown for me in the container, when the application is running in fullscreen, but i do see it, when its not running in fullscreen.
