### ISSUE TITLE
Feature: Maximum FPS setting.

### ISSUE THREAD

**Issue by exaiyo** [TNTwise/REAL-Video-Enhancer#39]
I noticed when using Flowframes app that you could set a maximum FPS setting so that if you want to interpolate from 24FPS to 60FPS, you could do so. In this RVE app, I only see 2x, 3x(72FPS), etc.

Is that a possibility with this RVE app?

Thanks for the great app regardless.

**Comment by TNTwise** [comment]
It has basic 24->60 functionality but this is not recommended as ffmpeg deletes whatever frames it wants, and not just interpolated frames.
If you still want to do it, modify the number inside the spinbox for interpolation factor to something like 2.5.
