### ISSUE TITLE
Custom model does not show

### ISSUE THREAD

**Issue by CounterFlow64** [TNTwise/REAL-Video-Enhancer#41]
Before submitting an issue, please confirm it meets all the criteria
- [*] I am on a distribution that is at least Ubuntu 20.04+, this means that your distros packages are the same as, or more up to date than Ubuntu 20.04, Or using Windows 10/11.

**Describe the bug**
When I import a custom model for upscaling, it does not appear. This is a 1x denoising model. Neither pytorch or the tensorrt option shows it

**To Reproduce**
Import a .pth model, and look at custom models in the upscale section

**Expected behavior**
I expected the model to appear

**Screenshots**

![image](https://github.com/user-attachments/assets/5ca3a7fe-ca76-4775-9819-d818613cc38a)

![image](https://github.com/user-attachments/assets/2bbbe6e3-85c2-4f3b-9318-0561709ff591)

![image](https://github.com/user-attachments/assets/75c27d3d-00fe-48a4-a3f9-c077b6f8cec5)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 41
 
**GPU**
RTX 3090 using tensorrt or pytorch

**Comment by TNTwise** [comment]
Make sure it has 1x or x1 in the name, I might have incorrectly handled that case.

**Comment by CounterFlow64** [comment]
Yes, thanks, it shows after that! Now, if only tile mode supported more than a resolution of 256, that uses almost nothing of my VRAM and the images are artifacty.

**Comment by TNTwise** [comment]
I'll add more tiling options, thanks for reporting.
