### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by IsaiMondiz** [TNTwise/REAL-Video-Enhancer#44]
The report is to find out if this is real, the antivirus suddenly jumps telling me that the file is infected

![image](https://github.com/user-attachments/assets/99043607-d3fd-448b-94b2-63acb72a9a48)

**Comment by TNTwise** [comment]
Yes, this is mentioned in the readme. It's caused by PyInstaller. The build system and code are all open source, with instructions to build in the readme if you don't trust the prebuilt binaries, you can build it yourself.
