### ISSUE TITLE
No backends other than NCNN Vulkan on Flatpak

### ISSUE THREAD

**Issue by ToniLipponen** [TNTwise/REAL-Video-Enhancer#45]
I'm running REAL-Video-Enhancer on Nobara 40 (based on Fedora 40) using the Flatpak version, and the only available backend is NCNN Vulkan. I have an RTX 2070 GPU, and I would like to use TensorRT if possible. But all other backends are greyed out, and can't be installed. 

![image](https://github.com/user-attachments/assets/ff9da8dd-c4e4-4fab-83e8-7817a8a7a8ea)

System Info:
 - OS: Nobara Linux 40 (Fedora 40)
 - GPU: Nvidia RTX 2070
 - Nvidia driver version: 560.35.03
 - Kernel version: 6.11.7
 - Flatpak version: 1.15.8

**Comment by TNTwise** [comment]
Flatpak has an issue where the storage free thats reported is not the actual free storage, I put in an issue <a href='https://github.com/flatpak/flatpak/issues/5924'>here</a> that got no responses. Currently the only backend that can fit comfortably within any reported storage is NCNN. Please use the executable from the releases tab for Cuda/TensorRT support.

**Comment by lxndr** [comment]
Hi! I've read the flatpak issue thread, and I wanted to say that I had issues about "no space left" for flatpak apps. For me, it was indeed systemd that creates a limited tmpfs for each user. I was able to fix it by [increasing tmpsfs size](https://askubuntu.com/a/876610). So I think you can probably enable the download buttons and simply show a message if there's no space left.

Thanks for great app!

**Comment by TNTwise** [comment]
@lxndr thanks for the suggestion! I added checks to see if the user has greater than 10gb available, and it worked. Pytorch and tensorrt support will be in the next flatpak stable release.
