### ISSUE TITLE
Feature: RealPLKSR support

### ISSUE THREAD

**Issue by InanimateCrbnRod** [TNTwise/REAL-Video-Enhancer#46]
First off, this app is so much better than Topaz already, thank you!!! secondly, are there plans to support realplksr models? There are some really nice ones I'd love to try on video. Thanks!

**Comment by TNTwise** [comment]
You can currently import a custom model in the download settings, and it works with all spandrel supported architectures (including realplksr). RealPLKSR only works with the pytorch backend, so you would need an nvidia card.

**Comment by InanimateCrbnRod** [comment]
Oh amazing! I was using the wrong backend. Thank you, this can be closed then.
