### ISSUE TITLE
Tensor RT model Optimizer not installed

### ISSUE THREAD

**Issue by Juddex0** [TNTwise/REAL-Video-Enhancer#47]
Hi, after installing the tensor RT backend for RVE, in the cli i encountered this warning;

WARNING:torch_tensorrt.dynamo.conversion.aten_ops_converters:Unable to import quantization op. Please install modelopt library (https://github.com/NVIDIA/TensorRT-Model-Optimizer?tab=readme-ov-file#installation) to add support for compiling quantized models

Is it normal for this to happen ?, if not, how i do install the model-opt library specifically to RVE ?

I have tried following the github instruction by using Microsoft's olive but it doesn't seem to work. Any help would be appreciated thank you :)

OS: Windows 11

My REAL-Video Enhancer folder is in "C:/"

**Comment by TNTwise** [comment]
Yes, that is normal. Just a warning and can be ignored, tensorrt should work perfectly fine as long as there is enough vram and it is an RTX card.

**Comment by Juddex0** [comment]
Got it, thank you for the quick reply

**Comment by TNTwise** [comment]
filtering out this warning on the front end to prevent confusion
