### ISSUE TITLE
Implement Import custom ONNX model option?

### ISSUE THREAD

**Issue by zelenooki87** [TNTwise/REAL-Video-Enhancer#48]
Upscaling onnx models are mostly universaly compatible.
Chainner loads almost all onnx upscaling models I have tried, even for white balance etc.
Could you please implement universal onnx support?

**Comment by TNTwise** [comment]
I have no plans to do this currently, as onnx is packaged differently than torch.

**Comment by zelenooki87** [comment]
It would be damn cool to support custom onnx models and utilising batch with tensorrt. please support it :) in near future if cannot now :)

**Comment by TNTwise** [comment]
That would require much reworking of the backend, just use the pth of whatever onnx you want.
