### ISSUE TITLE
upscale not working

### ISSUE THREAD

**Issue by YuryenUcahh** [TNTwise/REAL-Video-Enhancer#49]
I use fedora 41 workstation

Upscaling not working but interpolation working

![image](https://github.com/user-attachments/assets/f5693da8-ae31-4cf3-a49d-d1612fe8784d)

[backend_log.txt](https://github.com/user-attachments/files/18084721/backend_log.txt)
[frontend_log.txt](https://github.com/user-attachments/files/18084722/frontend_log.txt)

 
**GPU**
RX6700XT PYTORCH Rocm

"I already tried reinstalling"

**Comment by TNTwise** [comment]
Should be fixed in latest pre-release after it builds. Re-install rve and rocm. Use ncnn for now if that doesn't fix it.

**Comment by YuryenUcahh** [comment]
> Should be fixed in latest pre-release after it builds. Re-install rve and rocm. Use ncnn for now if that doesn't fix it.

It's working, thanks.
