### ISSUE TITLE
Video Upscaling Not Working in Flatpak Version on Manjaro

### ISSUE THREAD

**Issue by imakesound** [TNTwise/REAL-Video-Enhancer#7]
Before submitting an issue, please confirm it meets all the criteria
- [ ] I am on a distribution that is at least Ubuntu 20.04+, this means that your distros packages are the same as, or more up to date than Ubuntu 20.04.
- [x ] I am using the Flatpak or stable AppImage release, if you are on the BETA, please create an issue in that respective repository.

**Describe the bug**
I am experiencing an issue with upscaling video resolutions using the Flatpak version of the software on Manjaro Linux. Despite selecting various upscaling models such as RealESRGAN, RealCUGAN, and Waifu2x, the output video's resolution remains unchanged. The process completes without any errors, but the expected increase in resolution does not occur.

**To Reproduce**
Launch the application using the Flatpak package on Manjaro Linux.
Select a video file for upscaling.
Choose any of the upscaling models (RealESRGAN, RealCUGAN, or Waifu2x).
Start the upscaling process.
Upon completion, check the output video's resolution.

**Expected behavior**
I expected the resolution of the output video to be increased according to the selected upscaling model. Regardless of the model chosen (RealESRGAN, RealCUGAN, or Waifu2x), the resolution should have been enhanced, but it remains the same as the original.

**Screenshots**
![Screenshot from 2024-02-20 13-59-02](https://github.com/TNTwise/REAL-Video-Enhancer/assets/142548520/2b095806-b6e5-4fc1-a1c1-0d01fec7707e)
![Screenshot from 2024-02-20 14-00-16](https://github.com/TNTwise/REAL-Video-Enhancer/assets/142548520/22b34392-408c-465f-a895-d4167e980eea)

**Logs**
If the application generates a log, please upload it here.
[log_2024-02-20:13:55:52.txt](https://github.com/TNTwise/REAL-Video-Enhancer/files/14351651/log_2024-02-20.13.55.52.txt)

Logs folder on Flatpak: ``/home/$USER/.var/app/io.github.tntwise.REAL-Video-Enhancer/logs/``
Logs folder on AppImage: ``/home/$USER/.local/share/REAL-Video-Enhancer/logs/``

**Desktop (please complete the following information):**
 - OS: Manjaro linux 6.5.13-7-MANJARO
 - Version Flatpak
 
**GPU**
Please state your GPU, support on NVIDIA is difficult as I lack testing hardware, please be understanding if it is a problem relating to NVIDIA.
RTX4090

**Additional context**

**Comment by TNTwise** [comment]
thanks for catching, ill be sending out a patch within the next hour

**Comment by TNTwise** [comment]
fixed in latest appimage, i didnt test that either so dont worry there will be more really dumb bugs

**Comment by imakesound** [comment]
> thanks for catching, ill be sending out a patch within the next hour

Thank you for developing such an incredible software! It's truly a game changer, allowing me to avoid the need for maintaining a Windows machine just for these tasks.

**Comment by TNTwise** [comment]
flathub should update within the next 24 hours
