### ISSUE TITLE
Nothing is being output

### ISSUE THREAD

**Issue by Shotweb** [TNTwise/REAL-Video-Enhancer#8]
Before submitting an issue, please confirm it meets all the criteria
- [x ] I am on a distribution that is at least Ubuntu 20.04+, this means that your distros packages are the same as, or more up to date than Ubuntu 20.04.
- [x ] I am using the Flatpak or stable AppImage release, if you are on the BETA, please create an issue in that respective repository.

**Describe the bug**
No file is actually being created by the program.

When choosing the input file, it is correctly getting registered in the status window (top right corner). But not when choosing output folder.

After upscaling my video, the status window says "Finished! Output video: /home/shotweb/Videos//out.avi_1408x1024.mp4
Total Time: 0:01:42"

I assume the problem is the extra slash? And it's something flatpak related, but I'm not smart enough to think further.

**To Reproduce**
Try to upscale video.

**Expected behavior**
File of the updated video is created in the specified output folder.

**Screenshots**
N/A

**Logs**
If the application generates a log, please upload it here.
Logs folder on Flatpak: ``/home/$USER/.var/app/io.github.tntwise.REAL-Video-Enhancer/logs/``
Logs folder on AppImage: ``/home/$USER/.local/share/REAL-Video-Enhancer/logs/``

**Desktop (please complete the following information):**
 - OS: KDE Neon
 - Version: Flatpak
 
**GPU**
Radeon RX 6800 XT

**Additional context**
It also wants to change the file extension from avi to mp4.
[log.txt](https://github.com/TNTwise/REAL-Video-Enhancer/files/14470524/log.txt)

**Comment by TNTwise** [comment]
This can happen when the videos directory doesn't exist, or flatpak does not have required permissions to access the videos directory. I would recommend using the appimage instead.

**Comment by Shotweb** [comment]
You're right, I solved it with the terminal command `sudo flatpak override io.github.tntwise.REAL-Video-Enhancer --filesystem=/home/shotweb/Videos`
